### ISSUE TITLE
async_read_until returns before delimiter is found, but no error

### ISSUE THREAD

**Issue by Halt001** [TorstenRobitzki/Sioux#22]
Hi,

I've been playing around with your test socket class and I found that if it is used with Asio's **_async_read_until()_**, it will cause Asio to call the handler before the actual delimiter is found even though there is no delimiter in the data.

What happens is that Asio will repeatedly call **_undelayed_async_read_some()_** on the test socket and when the data is exhaused you will post an** _ec(boost::system::errc::success)_** and **_size(0)_** to the io_service queue. This will cause Asio to stop reading and call the handler because size==0. But since there is no error, the handler is called as if everything is OK and a delimiter was found.

Am I doing something wrong or should your **_undelayed_async_read_some()_** either not post a result or post an error when the test data is exhaused?

Thanks for letting us use this test code.

Cheers,

Tim

**Comment by TorstenRobitzki** [comment]
Hi Tim,
I'm going to write a test case that will try to cover the bug that you've discovered. From your description, I can't see why using asyc_read_until() should not work with the mock. Can you give me the boost version, where you have discovered this issue?

cheers,
Torsten

**Comment by Halt001** [comment]
I'm using Boost 1.60.0

**Comment by Halt001** [comment]
In file: ...\boost_1_60_0\boost\asio\impl\read_until.hpp at line 624 Asio makes the decision to quit trying to search for the delimiter and continue if either an error or 0 bytes were received. This results in the handler being called with the ec you provided (successful) and the number of bytes read so far (result_n).

**Comment by TorstenRobitzki** [comment]
Well, if the end of the stream is reached, that's equal to a graceful disconnect. You can only test 4 different situations:
* the delimiter is found
* the stream ends before the delimiter is found
* the connection is disconnected
* a timer fires and indicates, that your application is not going to wait any longer.

What would we expect in all of this 3 situations?
* Calling the read callback, indicating no error, reporting the size read
* Calling the read callback, indication no error, reporting zero bytes read
* Calling the read callback, indication an error.
* Calling the timer callback.

So I think the test socket is behaving correctly. What do you think?

**Comment by Halt001** [comment]
What I expect is that as long as the socket doesn't disconnect but also doesn't have more data available, _Asio's async_read_until()_ should not call the handler until the socket is disconnected or more data becomes available. I think this also happens with a 'real' connection.

If the test_socket behaves this way one can test if timeout is handled correctly.

In any case _Asio's async_read_until()_ should IMHO never call the handler without an error if the delimiter was not found, otherwise your code derails because it assumes the delimiter was read.

**Comment by TorstenRobitzki** [comment]
There is a special thing, we have to keep in mind, when testing: We have to define the whole scenario upfront, then run the test and then check, if the expectations where met.

So you, can not test a connection, that send some data (excluding the delimiter) and then stops to send data. The scenario have to end by a disconnect or a timeout, otherwise the test will never come to an end.

I can not say, how async_read_until() will behave, when a graceful disconnect comes before the delimiter is received. But if it's not behaving like you have tested it, there must be some translation from `success` and 0 bytes received to an error code. And I doubt, that this translation will be somewhere in the socket implementation.

Maybe we should do some testing with real connections. I'm going to see what happens on OS/X. Maybe you can do that test on your target platform?

**Comment by TorstenRobitzki** [comment]
I think I got it now. I case, the stream ends, the test socket should simulate an error code of boost::asio::error::eof, not success.

**Comment by Halt001** [comment]
If you allow your test to block the main thread you can stop sending without disconnecting. If you block longer than the timeout you're testing you should be able to get this in a test. I know that this is not exactly unit testing but it is still valuable.

_**boost::asio::error::eof**_, might be more apropriate for when the connection actually closes. But no data doesn't mean that the connection is gone yet. I've changed your code to just not  post anything to the queue. This will cause read operations to block until something closes the connection. But I'm not yet absolutely sure this is the correct way.

**Comment by TorstenRobitzki** [comment]
To not block, is one of the main purposes of asio_test. And that's why the socket and the timers have to be mocked during tests. The sioux unit tests would take hours, if the tests wouldn't use mocked timers.

Is this text (http://robitzki.de/blog/Asio_Mocks) readable, when you use google translate?
